kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install afl
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin && opam update
  - opam switch 4.07+afl
  - opam pin add -n .
  - opam depext asn1-combinators
  - opam install -y .
  - opam pin add -n bun https://github.com/yomimono/ocaml-bun.git
  - opam install -y bun
  - opam exec -- dune build @bun-fuzz --no-buffer
